services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  backend:
    volumes:
      # Container setup
      - ~/dev/devcontainer-setup/:/home/myuser/devcontainer-setup
      # Kiro
      - ~/.kiro:/home/myuser/.kiro
      - ~/install/kirocli/:/home/myuser/kirocli
      - ~/.local/share/kiro-cli/:/home/myuser/kirocli-data
      # Kilocode CLI
      - ~/.kilo:/home/myuser/.kilo
      - ~/.config/kilo:/home/myuser/kilo/config
      - ~/.local/state/kilo/:/home/myuser/kilo/state
      - ~/.local/share/kilo:/home/myuser/kilo/share
      # Atuin
      - ~/.atuin:/home/myuser/.atuin
      - ~/.config/atuin:/home/myuser/atuin/config
      - ~/.local/share/atuin:/home/myuser/atuin/data
      - ~/.bash-preexec.sh:/home/myuser/.bash-preexec.sh
    working_dir: /workspaces/backend

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Add a name for the host so that we can use kiro-gateway, etc.
    extra_hosts:
      - "host.docker.internal:host-gateway"
 
